notifications:
  email:
    recipients:
      - sebastian@jaenicke.org

language: java

dist: trusty

jdk: oraclejdk8

branches:
  only:
    - master

cache:
  directories:
  - $HOME/.m2

script:
  - mvn clean install
