notifications:
  email:
    recipients:
      - sebastian@jaenicke.org

language: java

dist: bionic

sudo: required

jdk: oraclejdk11

branches:
  only:
    - utilities_2_0

cache:
  directories:
  - $HOME/.m2

env:
  global:
  - TARGET_REPO="github.com/MGX-metagenomics/MGX-gui.git"

before_install:
  - sudo add-apt-repository -y ppa:maarten-fonville/protobuf
  - sudo apt-get update -qq
  - sudo apt-get install -qq protobuf-compiler
  - sudo ln -s /usr/bin/protoc /usr/bin/protoc-3

script:
  - mvn clean install

after_success: |
  if [ -n "$GITHUB_API_KEY" ]; then
    cd "$TRAVIS_BUILD_DIR"
    # fetch KEGG data
    cd KEGG-Pathways/target && java -jar KEGG-Pathways-2.0.jar
    git clone -b MGX_gui_2_0 git://${TARGET_REPO}
    SRC=/tmp/kegg/kegg.mv.db
    TRG="MGX-gui/MGX-KeggViewer/src/main/resources/de/cebitec/mgx/gui/keggviewer/kegg.mv.db"
    if [ ! $(cmp -s ${SRC} ${TRG} ) ]; then
      MESSAGE="Automatic KEGG database update via Travis CI build #${TRAVIS_BUILD_NUMBER}."
      git config --global user.name "Travis CI"
      git config --global user.email "travis@travis-ci.org"
      cp ${SRC} ${TRG}
      cd MGX-gui
      git commit -m "${MESSAGE}" MGX-KeggViewer/src/main/resources/de/cebitec/mgx/gui/keggviewer/kegg.mv.db
      git push -q "https://${GITHUB_API_KEY}@${TARGET_REPO}" MGX_gui_2_0 || echo "Git push failed."
    else
      echo "KEGG database unchanged."
    fi
  else
    echo "No GitHub API key found."
  fi
  if [ -n "$PKG_DEPLOY_TOKEN" ]; then
    cd "$TRAVIS_BUILD_DIR"
    mvn deploy -Dregistry=https://maven.pkg.github.com/MGX-metagenomics -Dtoken="$PKG_DEPLOY_TOKEN"
  else 
    echo "No deploy token available."
  fi
