
name: KEGG database update

#
# update the KEGG sqlite database every three months
#

on:
  schedule:
    - cron: '0 0 1 1,3,6,9,12 *'
  workflow_dispatch:

jobs:
  update-kegg-db:

    permissions:
      contents: write

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        ref: utilities_2_0
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Setup mvn cache
      uses: actions/cache@v3
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-mgx-cache
    - name: Compile 
      run: |
        mvn clean install -N
        mvn clean install -DskipTests=true --file JFreeSVG-OSGi/pom.xml
        mvn clean install -DskipTests=true --file RESTEasy-OSGi/pom.xml
        mvn clean install -DskipTests=true --file KEGG-Pathways/pom.xml
    - name: Create new KEGG database
      run: java -jar KEGG-Pathways/target/KEGG-Pathways-2.0.jar
    - name: Run KEGG CI tests
      run: |
        cp /tmp/kegg/kegg.db KEGG-Pathways/src/main/resources/de/cebitec/mgx/kegg/
        mvn -B package --file KEGG-Pathways/pom.xml
    - name: Commit KEGG database
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
        git diff --quiet || git commit -m "Automated KEGG database update [ci skip]" KEGG-Pathways/src/main/resources/de/cebitec/mgx/kegg/kegg.db
        git push

